version: "3.8"
services:
  server:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - valkey
      - qdrant
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
